#!/usr/bin/env node
// =============================================================================
// Offline generator for Data/SpellDB.lua -- NOT loaded by the game, run this
// manually whenever you want to refresh the "Add spell" search index.
//
// SOURCE: SimulationCraft's SpellDataDump/allspells.txt -- a plain-text dump
// of the spell data simc extracts from the WoW game client's own DB2 files,
// regenerated by the simc team for every client build. One curl from GitHub,
// no API keys. This replaced the original Battle.net Game Data API walk
// (see git history), which could only reach class/spec/hero/pvp TALENT
// spells (~3k) and missed every baseline ability (Kick, Pummel, Counterspell,
// Fear, ...). The simc dump has ~31k spells including baseline abilities,
// PvP talents, trinket/item effects, and separately-id'd aura spells.
//
// KNOWN COVERAGE LIMITS (verified against the real dumps, 2026-07-05):
//   * The dump is simc's combat-sim whitelist, not literally every spell in
//     the client (~413k ids exist) -- a few sim-irrelevant baseline spells
//     are missing, e.g. Polymorph (118). EXTRA_SPELLS below hand-patches the
//     known gaps; add to it if a search comes up empty for a real spell.
//   * Cast id vs aura id: when a cast applies its aura via its own
//     "Apply Aura" effect (the common case -- Kingsbane 385627 included,
//     despite an earlier note here claiming its debuff was 192853; the simc
//     effect data shows 385627 applies the periodic damage itself), the aura
//     id IS the cast id and search Just Works. Where a cast triggers a
//     separately-id'd spell, that spell is usually in the dump under the
//     same name (both ids will show in search -- add both, keep the one that
//     lights up). Only server-side script-applied auras are unknowable from
//     any data source; for those, look up the aura id on Wowhead and type it.
//
// WoW addons cannot make network requests, so this can't run in-game -- run
// it from your machine; it writes a plain Lua data file the addon loads
// normally.
//
// Usage:
//   node Tools/generate_spelldb.js                  # fetch simc "midnight" branch
//   node Tools/generate_spelldb.js --branch thewarwithin
//   node Tools/generate_spelldb.js --file /path/to/allspells.txt   # offline
//
// Pick the branch matching your live client's expansion (the generated file
// header records the client build the dump was made from). Requires Node 18+
// (global `fetch`). No npm dependencies.
// =============================================================================

const fs = require('fs');
const path = require('path');

const OUT_PATH = path.join(__dirname, '..', 'Data', 'SpellDB.lua');
const DEFAULT_BRANCH = 'midnight';

// Real, currently-obtainable spells verified missing from simc's whitelist
// (it only extracts what matters for combat simulation). Checked 2026-07-05
// against the midnight branch dump; extend as gaps are found.
const EXTRA_SPELLS = [
    { id: 118, name: 'Polymorph' },
    { id: 20066, name: 'Repentance' },
    { id: 115268, name: 'Mesmerize' }, // succubus pet
    { id: 132409, name: 'Spell Lock' }, // Grimoire of Sacrifice version
];

function parseArgs(argv) {
    const opts = { branch: DEFAULT_BRANCH, file: null };
    for (let i = 2; i < argv.length; i++) {
        if (argv[i] === '--branch' && argv[i + 1]) opts.branch = argv[++i];
        else if (argv[i] === '--file' && argv[i + 1]) opts.file = argv[++i];
        else {
            console.error(`Unknown argument: ${argv[i]}`);
            console.error('Usage: node Tools/generate_spelldb.js [--branch <simc-branch>] [--file <allspells.txt>]');
            process.exit(1);
        }
    }
    return opts;
}

async function loadDump(opts) {
    if (opts.file) {
        console.log(`Reading ${opts.file}...`);
        return fs.readFileSync(opts.file, 'utf8');
    }
    const url = `https://raw.githubusercontent.com/simulationcraft/simc/${opts.branch}/SpellDataDump/allspells.txt`;
    console.log(`Fetching ${url}...`);
    const res = await fetch(url);
    if (!res.ok) {
        throw new Error(`Download failed: HTTP ${res.status} -- check the branch name (e.g. midnight, thewarwithin).`);
    }
    return res.text();
}

// Dump entries open with lines like:
//   Name             : Kick (id=1766) [Spell Family (8)]
//   Name             : Precognition (id=377360) [Passive]
//   Name             : Mass Polymorph (desc=Utility) (id=361095) [Spell Family (227)]
// Greedy match anchors on the LAST "(id=N)" so parenthesized names survive;
// the "(desc=...)" qualifier is stripped. [Hidden]/[Passive] entries are
// deliberately KEPT -- separately-id'd aura spells are often flagged
// Hidden/Not In Spellbook and are exactly what aura tracking needs.
const NAME_LINE_RE = /^Name\s*:\s(.*) \(id=(\d+)\)/;

function parseDump(text) {
    const found = new Map(); // id -> name
    let build = null;
    for (const line of text.split('\n')) {
        if (build === null && line.startsWith('SimulationCraft')) build = line.trim();
        const m = line.match(NAME_LINE_RE);
        if (!m) continue;
        const id = Number(m[2]);
        const name = m[1].replace(/\s*\(desc=[^)]*\)$/, '').trim();
        if (name) found.set(id, name);
    }
    return { found, build };
}

async function main() {
    const opts = parseArgs(process.argv);
    const text = await loadDump(opts);
    const { found, build } = parseDump(text);

    if (found.size < 1000) {
        throw new Error(
            `Parsed only ${found.size} spells -- the dump format may have changed; inspect NAME_LINE_RE against the file.`
        );
    }

    for (const extra of EXTRA_SPELLS) {
        if (!found.has(extra.id)) found.set(extra.id, extra.name);
    }

    const entries = [...found.entries()].sort((a, b) => a[0] - b[0]);
    const lines = [
        'local addonName, ID = ...',
        '',
        '-- Generated by Tools/generate_spelldb.js -- do not hand-edit.',
        '-- Regenerate with: node Tools/generate_spelldb.js',
        `-- Source: ${build || 'unknown simc build'}`,
        'ID.SpellDB = {',
        ...entries.map(([id, name]) => `    { id = ${id}, name = ${luaStringLiteral(name)} },`),
        '}',
        '',
    ];

    fs.writeFileSync(OUT_PATH, lines.join('\n'));
    console.log(`\nWrote ${entries.length} spells to ${OUT_PATH}`);
    console.log(`Source: ${build || 'unknown'}`);
}

function luaStringLiteral(s) {
    return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
